name: CI for FontInfo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/FontInfo.sln
    - name: Build
      run: dotnet build src/FontInfo.sln --no-restore
    - name: Test
      run: dotnet test test/FontInfoTests/FontInfoTests.csproj --no-build --verbosity normal