name: Build and Publish package

on: workflow_dispatch  

jobs:
  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/FontInfo.sln
    - name: Build
      run: dotnet build src/FontInfo.sln --no-restore  --configuration Release
    - name: Test
      run: dotnet test test/FontInfoTests/FontInfoTests.csproj --no-build --verbosity normal --configuration Release
      
    - name: Publish NuGet  
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/FontInfo/FontInfo.csproj        
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}